### ISSUE TITLE
json export 2nd time a bytes-like objects is required

### ISSUE THREAD

**Issue by electrocoder** [matesh/mqttk#9] opened 2022-10-10 08:54 UTC
When I run json for the 2nd time, I get an error.
![image](https://user-images.githubusercontent.com/628144/194830223-d930605c-1724-4dc2-9946-edbf0f231bfb.png)

**Comment by matesh** [comment] 2022-10-10 09:50
Thank you for reporting, this will be fixed as part of the ongoing rework on exporting messages.

**Comment by electrocoder** [comment] 2022-10-10 09:57
The source of the problem is trying to give the lines converted to base64 again, it was solved by adding try except.
            if format == "JSON":
                messages = list(self.subscribe_frame.messages.values())
                for message in messages:
                    try:
                        message["payload"] = base64.b64encode(message["payload"]).decode("utf-8")
                    except:
                        pass

**Comment by matesh** [comment] 2022-10-10 10:08
Well that's not the underlying issue, if you look at the message list after the first JSON export, you notice that all of the messages in the message library are converted to base64, so when you go and select a message from the message list, the content appearing is in base64. The issue is with referencing, the `list(self.subscribe_frame.messages.values())` is just a list of references, not a copy of the dictionary items, and the conversion is persistent. However, this has been eliminated in the version i'm working on, I just need to get about and finish it.

**Comment by matesh** [comment] 2022-10-17 17:54
This has now been fixed, you can try the test branch

**Comment by electrocoder** [comment] 2022-10-17 18:59
> This has now been fixed, you can try the test branch

test branch "as json" and "as csv" not working, 
my system mac os monterey
python 3.10

**Comment by matesh** [comment] 2022-10-17 19:01
Can you please elaborate?

**Comment by electrocoder** [comment] 2022-10-17 19:05
> Can you please elaborate?

app crashes

**Comment by matesh** [comment] 2022-10-17 19:09
Please describe at which point it crashes, and if you can reproduce, please run the __main__.py from your terminal and paste the output in here. I'm on the same OS & interpreter and have no issues.

**Comment by electrocoder** [comment] 2022-10-17 19:19
CFatal Python error: PyEval_RestoreThread: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: initialized

Thread 0x0000700010c69000 (most recent call first):
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 3772 in insert
  File "/Users/sahin/Downloads/mqttk-test/mqttk/widgets/subscribe_tab.py", line 379 in on_message_select
  File "/Users/sahin/Downloads/mqttk-test/mqttk/widgets/subscribe_tab.py", line 320 in add_message
  File "/Users/sahin/Downloads/mqttk-test/mqttk/widgets/subscribe_tab.py", line 461 in add_new_message
  File "/Users/sahin/Downloads/mqttk-test/mqttk/widgets/subscribe_tab.py", line 478 in on_mqtt_message
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3556 in _handle_on_message
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327 in _handle_publish
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033 in _packet_handle
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439 in _packet_read
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556 in loop_read
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164 in _loop
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756 in loop_forever
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591 in _thread_main
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973 in _bootstrap

Current thread 0x00000001066d0600 (most recent call first):
  File "/Users/sahin/Downloads/mqttk-test/mqttk/widgets/subscribe_tab.py", line 511 in get_messages
  File "/Users/sahin/Downloads/mqttk-test/mqttk/__main__.py", line 405 in export_messages
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921 in __call__
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1458 in mainloop
  File "/Users/sahin/Downloads/mqttk-test/mqttk/__main__.py", line 451 in main
  File "/Users/sahin/Downloads/mqttk-test/mqttk_entry.py", line 3 in <module>

**Comment by matesh** [comment] 2022-10-17 19:23
Looks like you are not using the system interpreter, the error doesn't seem to come from an error in the code itself. I used to have this craash when I used an incorrect interpreter. If you clone the master branch, does it run or it crashes the same way?

**Comment by electrocoder** [comment] 2022-10-17 19:37
master branch is succesfull

**Comment by matesh** [comment] 2022-10-17 19:41
Can you please describe what you are doing exactly so I can try to reproduce?

**Comment by electrocoder** [comment] 2022-10-17 19:50
connect and subscribe later app crashes :/

<img width="505" alt="image" src="https://user-images.githubusercontent.com/628144/196268624-1653374a-1201-4044-b50e-0ae8ad63f5c6.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/628144/196269069-74fff483-1086-4faf-adcc-c98a16f23cf0.png">

**Comment by matesh** [comment] 2022-10-17 19:52
I was unable to reproduce this. Looking at the stacktrace, the interpreter seems to be crashing where i'm using the threading.Lock. Try cloning the test branch again, I replaced it with the Lock from multiprocessing.

**Comment by electrocoder** [comment] 2022-10-17 19:59
> I was unable to reproduce this. Looking at the stacktrace, the interpreter seems to be crashing where i'm using the threading.Lock. Try cloning the test branch again, I replaced it with the Lock from multiprocessing.

the crash continues

**Comment by electrocoder** [comment] 2022-10-17 20:00
> > I was unable to reproduce this. Looking at the stacktrace, the interpreter seems to be crashing where i'm using the threading.Lock. Try cloning the test branch again, I replaced it with the Lock from multiprocessing.
> 
> the crash continues

i will try windows 10 tomorrow

**Comment by matesh** [comment] 2022-10-17 20:01
Could you also perhaps try your system interpreter?

**Comment by matesh** [comment] 2022-10-18 08:05
I tested this morning on Windows, Linux and two Conda interpreters, not a single issue. I think this is specific to your build of interpreter, which seems to be crashing.

**Comment by electrocoder** [comment] 2022-10-18 08:54
[<iframe width="560" height="315" src="https://www.youtube.com/embed/lJfGJtd2IZY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>](https://youtu.be/lJfGJtd2IZY)

**Comment by matesh** [comment] 2022-10-18 09:21
Ok, this was helpful and I was able to reproduce the issue. I always tested exporting while not being subscribed to anything, or subscriptions being muted. 

I'm not sure why the locks are not working properly. There's an issue with the paho-mqtt library that I'm aware of, when its main loop is blocked for too long, it hangs. This might be at play here too, it acquired the lock but never finished to return it.

Check the test branch, should work now. Note that incoming messages arriving while exporting are dropped. I'll look into how this could be made a bit more efficient, but at least it should not crash now.

**Comment by electrocoder** [comment] 2022-10-18 11:19
> Ok, this was helpful and I was able to reproduce the issue. I always tested exporting while not being subscribed to anything, or subscriptions being muted.
> 
> I'm not sure why the locks are not working properly. There's an issue with the paho-mqtt library that I'm aware of, when its main loop is blocked for too long, it hangs. This might be at play here too, it acquired the lock but never finished to return it.
> 
> Check the test branch, should work now. Note that incoming messages arriving while exporting are dropped. I'll look into how this could be made a bit more efficient, but at least it should not crash now.

![image](https://user-images.githubusercontent.com/628144/196415684-b787001d-fa80-4d47-b5f0-93df596d4423.png)

**Closed as completed** 2022-11-19 18:50 UTC
